import type { ElementLocator, RunFlowSummary, StepResult } from "./types";

// Pure formatting only — no LLM call. Renders the already-generated flow
// summary (src/server/flowSummary.ts) into the SKILL.md convention used by
// AI coding/browser agents: YAML frontmatter (name/description) followed by
// plain markdown instructions.
export function slugify(input: string): string {
  return input.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "skill";
}

function firstSentence(text: string, maxLen: number): string {
  const sentence = text.match(/^[^.!?]*[.!?]/)?.[0]?.trim() ?? text;
  return sentence.length > maxLen ? `${sentence.slice(0, maxLen - 1)}…` : sentence;
}

// Turns a captured ElementLocator (automation.ts) into the literal
// Playwright code a person (or an agent) would use to re-find the same
// element — the whole point of capturing it in the first place.
function formatPlaywrightLocator(locator: ElementLocator): string {
  const esc = (s: string) => s.replace(/'/g, "\\'");
  // Mirrors resolveLocator's scoping in src/server/locatorReplay.ts — the
  // weaker strategies (role/placeholder/text) get chained off the recorded
  // landmark ancestor when one was captured, instead of searching the whole
  // page, so the exported code matches what replay actually does.
  const scopable = locator.strategy === "role" || locator.strategy === "text" || locator.strategy === "placeholder";
  const root = scopable && locator.scopeSelector ? `page.locator('${esc(locator.scopeSelector)}')` : "page";
  switch (locator.strategy) {
    case "testId":
      return `page.getByTestId('${esc(locator.value)}')`;
    case "role":
      // exact: true — see the identical note in src/server/locatorReplay.ts;
      // without it this matches any element whose name merely *contains*
      // the recorded one.
      return `${root}.getByRole('${locator.role}', { name: '${esc(locator.value)}', exact: true })`;
    case "placeholder":
      return `${root}.getByPlaceholder('${esc(locator.value)}', { exact: true })`;
    case "text":
      return `${root}.getByText('${esc(locator.value)}', { exact: true })`;
    case "css":
      return `page.locator('${esc(locator.value)}')`;
  }
}

export function buildSkillsMd(params: {
  skillName: string;
  startUrl: string;
  promptText: string;
  status: string;
  runId: string;
  summary: RunFlowSummary;
  steps: StepResult[];
}): string {
  const { skillName, startUrl, promptText, status, runId, summary, steps } = params;
  const slug = slugify(skillName);
  const description = firstSentence(summary.narrative || promptText, 200);

  const stepByIndex = new Map(steps.map((s) => [s.index, s]));
  const stepCaptions = summary.stepCaptions.slice().sort((a, b) => a.index - b.index);

  function renderStep(text: string, index: number): string {
    const line = `${index + 1}. ${text}`;
    const step = stepByIndex.get(index);
    if (step?.locator) {
      return `${line}\n   - Target: \`${formatPlaywrightLocator(step.locator)}\``;
    }
    if (step?.x !== undefined && step?.y !== undefined) {
      return `${line}\n   - Coordinates: (${step.x}, ${step.y}) — viewport-relative, least durable option`;
    }
    return line;
  }

  const stepsMd = stepCaptions.length
    ? stepCaptions.map((c, i) => renderStep(c.caption, i)).join("\n")
    : summary.keySteps.length
      ? summary.keySteps.map((s, i) => `${i + 1}. ${s}`).join("\n")
      : "1. (no steps recorded)";

  const hasAnyTarget = steps.some((s) => s.locator || s.x !== undefined);

  return `---
name: ${slug}
description: ${description}
---

# ${skillName}

${summary.narrative}

## Start

Navigate to: ${startUrl}

## Steps

${stepsMd}

## Expected outcome

${summary.outcome || "Not specified."}

---

_Generated by agentic-knowledge-transfer from a recorded session (run \`${runId}\`, status: ${status}). Re-record and regenerate to keep this file in sync with the actual flow.${
    hasAnyTarget
      ? " \"Target\" locators were captured live during recording and are best-effort — verify against the current page before relying on them in an automated script. \"Coordinates\" are viewport-relative and the least durable option."
      : ""
  }_
`;
}
